### ISSUE TITLE
Hint: remote location

### ISSUE THREAD

**Issue by TylonHH** [b2un0/kodi-script-hyperion#1]
While starting I noticed, that the "hyperion-remote" binary should be
`/storage/hyperion/bin/hyperion-remote.sh` not as you posted on the screenshot.

**Comment by b2un0** [comment]
Screenshot is from OSMC

**Comment by TylonHH** [comment]
I see, you're right. Then you should mention that the RPi User should use the *.sh
But I guess there more prioritys now. ;-)

**Comment by b2un0** [comment]
Die Funktion fliegt eh raus, und warum machst du hier n Ticket wenn die Screenshots im Forum sind?
Außerdem steht im Forum auch bei was da eingegeben werden muss ;)

**Comment by TylonHH** [comment]
Weil mir Dein Projekt gefällt und ich es gerne (auch international) pushen möchte. Dafür ist doch github da, dass dann auch andere Prgrammierer es vorantreiben können. Oder?
Ich kann auch gerne im Forum weiter machen :-P

**Comment by b2un0** [comment]
Grundsätzlich stimme ich dir zu und sorry falls das gestern n bissl schnippig rüber kam :)
allerdings fehlt mir hier der Bezug deines Tickets, die Screenshots sind halt (noch) nicht hier.
Für das internationale puschen müsste man das Projekt im Wiki hier rechts mit auflisten
https://github.com/tvdzwan/hyperion/wiki

Vielleicht kann @brindosch da was im Wiki machen :)

**Comment by brindosch** [comment]
Plattformübergreifend: Es macht auf jedenfall Sinn das ganze von direkt Pfaden nach json umzuschreiben, um das Addon überall benutzen zu können. Im Zuge der "Forward" Funktion könnte man sogar soweit gehen und sagen, ich möchte das optional an mehrere Hyperion-Instanzen mit anderen Einstellungen/Aktionen senden.

Das json interface wird in den nächsten Monaten weiter ausgebaut, wahrscheinlich von RickDB.
Kann aber noch nichts dazu sagen.

International: Es macht ebenfalls Sinn keine strings die zu übersetzen wären "hard" zu coden sondern die strings in die entsprechende .xml auszulagern.
Edit: Hast du schon gemacht oder angefangen, gut!
In diesem Sinne eine deutsche Übersetzung und weitere. 
Das steht für das offizielle Addon auch noch an. Ich hatte bisher keine Zeit dafür. Ausserdem werden wir es danach in das offizielle Kodi repo schieben. Macht es nur einfacher.

Ob dieses "control" Addon eine gemeinsame Zusammenarbeit aller Entwickler die daran interessiert sind wird oder nicht, müsst ihr ausmachen.
Hyperion zieht bald in eine Github Organisation um, das macht es super einfach die repo Rechte zu verwalten. Entsprechend könntet ihr dann dort zusammen dran werkeln sofern Interesse besteht.
Ebenfalls könnten wir es auf diesem Weg dann auch in das offizielle Kodi Addon repo schieben.

Ist noch etwas Zukunftsmusik, ich freue mich aber über jeden Mithelfer der Hyperion im Ganzen versucht zu verbessern und komfortabler zu machen.

@TylonHH 
Die Android App hat eine Priority-Einstellung, wenn du auf deinen "Hyperion Server" Eintrag gehst. Ich weiß nicht, ob das auch für Effekte gilt oder nur für die color modification.
Die App brauch eh dringend ne Überarbeitung mit der nächsten Hyperion Version gibts ein großes Chaos, aber woher die Zeit nehmen und nicht stehlen

**Comment by b2un0** [comment]
Danke für deine Antwort @brindosch :)

Im dev branch ist es schon auf die JSON Kommunikation umgeschrieben und wir von mir aktuell so auch verwendet, es sind noch 1-2 kleinere Bugs vorhanden welche ich noch beheben muss.
Sobald das erledigt ist geht das als 0.0.6 raus und die ``<platform>linux</platform>`` Abhängigkeit fliegt raus.

Die Deutsche Übersetzung kommt dann natürlich auch demnächst, wahrscheinlich in dem Zug wo ich es hinbekommen habe das die Effektliste für die Optionen nicht mehr hardcoded ist sondern direkt bei Hyperion ausgelesen wird, hier muss ich aber erstmal weiter die Kodi implementieren verstehen.

Im Grunde ist das Projekt überhaupt meiner erster großer Gehversuch mit Python - dank PyCharm und Vorkenntnisse durch die PhpStorm IDE aber zum Glück nicht sooo kompliziert.

Ich hätte Grundsätzlich sogar nichts dagegen dieses Projekt dann ebenfalls mit in die Hyperion Organisation hier auf github zu verschieben, so können dann alle die wollen effektiver mit entwickeln.

Laut meinen Server logs für die Downloads wird das Addon mittlerweile auch von sehr vielen Leuten verwenden.

**Comment by brindosch** [comment]
Jetzt hab ich die eigentlich Frage nicht beantwortet.

Ihr könnt jederzeit eine "Anleitung" oder Präsentation/Vorstellungen im Rahmen eines Wiki Posts erstellen. Je besser die Funktionen dokumentiert sind je besser. Denn auch hier bekommt man nicht alle Erläuterungen oder Hinweise in das Einstellungs-Menü
Gerne könnt ihr eine deutsche und englische Fassung schreiben (sogar mit "deutschen" screenshots und "englischen" screenshots). Wieso? Das werdet ihr bald sehen :)
